# Generated by Django 5.2.7 on 2025-11-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EachUserChat',
        ),
    ]
